config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root "homes#index"
  post "/graphql", to: "graphql#execute"

  namespace :admin do
    devise_for :users, controllers: {
                         sessions: "admin/users/sessions",
                         registrations: "admin/users/registrations",
                         confirmations: "admin/users/confirmations",
                         passwords: "admin/users/passwords",
                       }
  end

  #For admin panel with react front-end
  namespace :api do
    namespace :v1 do
      namespace :admin do
        mount_devise_token_auth_for "User", at: "auth", controllers: {
                                              # registrations: "api/v1/admin/registrations",
                                              # confirmations: "api/v1/admin/confirmations",
                                              # passwords: "api/v1/admin/passwords",
                                              # sessions: "api/v1/admin/sessions",
                                              token_validations: "api/v1/admin/token_validations",
                                            }

        devise_scope :admin_user do
          #For token validation to show "Admin Dashboard" nav link in frontend
          get "auth/validate_cookies_token", to: "token_validations#validate_token"
        end
      end
    end
  end

  devise_scope :admin_user do
    get "login", to: "admin/users/sessions#new", as: :admin_login
    get "signup", to: "admin/users/registrations#new", as: :admin_signup
    get "update", to: "admin/users/registrations#edit", as: :admin_update
  end

  authenticate :admin_user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
    mount RailsAdmin::Engine => "/superadmin", as: "rails_admin"
    if Rails.env.development?
      mount GraphqlPlayground::Rails::Engine, at: "/playground", graphql_path: "/graphql"
    end
  end

  get "*path", to: "homes#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/user.rb
class User < ApplicationRecord
  include DeviseTokenAuth::Concerns::User
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  mount_uploader :profile_image, DocumentUploader
  enum role: { admin: "admin", viewer: "viewer" }
  before_validation :set_uid, on: :create
  validates :name, :role, :email, presence: true

  private

  def set_uid
    self.uid = email if uid.blank?
  end
end

app/controllers/admin/users/confirmations_controller.rb
# frozen_string_literal: true

class Admin::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/users/passwords_controller.rb
# frozen_string_literal: true

class Admin::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/users/registrations_controller.rb
# frozen_string_literal: true

class Admin::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, only: [:update]

  def create
    redirect_to "/home", alert: "Signup Not Allowed!"
  end

  def update
    super
  end

  def destroy
    redirect_to "/home", alert: "Account Deactivation Not Allowed!"
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(resource)
    if resource.admin?
      rails_admin_path
    else
      root_path
    end
  end

  def after_sign_in_path_for(resource)
    if resource.admin?
      rails_admin_path
    else
      root_path
    end
  end

  def after_inactive_sign_up_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])

    # unless params[:admin_user][:role]
    #   params[:admin_user][:role] = "admin"
    # end
  end
end

app/controllers/admin/users/sessions_controller.rb
class Admin::Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def create
    super do |resource|
      if resource
        token = resource.create_new_auth_token
        set_auth_cookies(token)
      end
    end
  end

  def destroy
    user = current_admin_user
    super do |_|
      if (client_id = (cookies.encrypted[:auth_headers] || "{}")["client"]) && user&.tokens[client_id]
        user.tokens.delete(client_id)
        user.save!
      end
      cookies.delete(:auth_headers)
    end
  end

  protected

  def set_auth_cookies(token)
    cookies.encrypted[:auth_headers] = {
      value: token,
      httponly: true,
      secure: Rails.env.production?,
      same_site: :lax,
    }
  end

  def after_sign_in_path_for(resource)
    if resource.admin?
      rails_admin_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/admin/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <section class="errors flash__message p-1 py-4 shadow-lg z-50 flex items-start gap-2" data-controller="removals" data-action="animationend->removals#remove">
    <div class="flash__header"></div>
    <i class="fa-solid fa-circle-exclamation text-[#E0115F] text-xl ml-2"></i>
    <div class="flex-1">
      <h6 class="text-[#E0115F] font-semibold">Error</h6>
      <div class="text-sm mt-1">
        <% resource.errors.full_messages.uniq.each do |message| %>
         <p class="flex items-start gap-2">
            <i class="fa-solid fa-caret-right text-[#E0115F] text-xs mt-1"></i> <%= message %>
          </p> 
        <% end %>
      </div>
    </div>

    <button class="text-gray-400 hover:text-gray-600 text-lg px-4" onclick="this.parentElement.remove()">✖</button>
  </section>
<% end %>

app/views/admin/users/shared/_links.html.erb
<% if controller_name != "sessions" %>
  <%= link_to "Log in", new_session_path(resource_name), class: "devise-btn login-btn" %><br />
<% end %>

<% if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "devise-btn signup-btn" %><br />
<% end %>

<% if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "devise-btn forgot-password-btn" %><br />
<% end %>

<% if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "devise-btn confirmation-btn" %><br />
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "devise-btn unlock-btn" %><br />
<% end %>

<% if devise_mapping.omniauthable? %>
  <% -resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false }, class: "devise-btn omniauth-btn" %><br />
  <% end %>
<% end %>